### ISSUE TITLE
As an Open Data Hub maintainer i want new providers to not end up in the router dead letter in order to distinguish between failed messages and not-yet-implemented transformers

### ISSUE THREAD

**Issue by Luscha** [noi-techpark/infrastructure-v2#26]

**Comment by Luscha** [comment]
Regarding this issue, it's about the router's behaviour on sending all messages to the deadletter without the ability to differentiate broken messages from messages sent by a work-in-progress pipeline without a transformer an thus without a destination queue for the route-key (composed by mongo's database-collection names).

After exploring the issue i came to the conclusion that thi is the only correct behaviour the process can have to maintain rabbitMQ consistency (and more in general the event driven paradigm).

There is in fact no way to distinguish a broken message from a message belonging to work-in-progress pipeline.
It's impossible to write a rule that routes "alperia.echarger" to a new queue and recognizes "654654.sdfss" as a broken message.

In addition, the whole idea behind a topic exchange is to delegate to the consumer the responsibility of creating the queue with the binding given its own interest. The RabbitMQ guidelines discourage the creation of topic exchange's bindings by the producer. Apache camel's component itself does not provide this capability out of the box and should be done with some custom code.

I therefore explored some "hacky" solutions to resolve this issue:

1. 
We could add a parameter to the message (the same way we did for fastline and push-update) so that the router knows that a message flagged with "force-queue" will force the router to create programmatically a queue and bind it to the "routed" exchanged using the route-key. This not only introduces the risk of misusage of the flag but also makes the router behaviour inconsistent.

In fact, the system is designed to allow messages to be captured by different pipelines. "alperia.echarge" could be a message of interest for a transformer processing the "echarge" only (route-key = "alperia.echarge") but also to a transformer interested in capturing all alperia's data (route-key = "alperia.*"). by forcing the creation of the queue with the flag we lose the elasticity to have multiple consumers.

2.
We could add the rule to the router to force it to create a queue using the first part of the route-key (alperia.echarge -> alperia.#) to add a "default queue" where the message can still be distinguished by provider even if they are unroutable. This solution won't scale well since: We duplicate all messages in production generating unnecessary space consumption and traffic and because we still can't distinguish broken messages with work-in-progress pipelines.

3.
We could create a dictionary of "allowed route-keys / provider" which sets a queue and bindings when the system starts up or when a message matching the whitelist arrives. This solution could work but the benefit of having the queue automatically set up is matched with the cons of having a hardcoded route table to manage.

It's worth mentioning that solutions 1 and 2 make the Deadletter completely irrelevant since all messages will always find a queue where to be routed, leading to the opposite problem: the impossibility of finding broken messages. It is also a major security issue because the amount of queues and bindings generated is out of our control, since broken messages could arrive with any route-key generating infinitely queues.


After this analysis, I think the most secure, elegant and consistent way to solve this issue is to create a python/bash script to manually create a queue-binding on-demand. This way the developer/engineer has control and only known messages (the one belonging to a work-in-progress pipeline) are routed to a different queue.

**Comment by clezag** [comment]
@Luscha I generally agree with your solution of creating scripts to do this on demand, and I think it's absolutely workable to start on. There isn't really anything stopping us from adding something later if we really want to.

**Comment by Luscha** [comment]
Ok! I'll then proceed with a simple script.
Do you have any preference with the language? will python work or would it be better a bash script?

**Comment by clezag** [comment]
Python sounds good!
