### ISSUE TITLE
As an Open Data Hub developer i want to be able to perform integration test on my local machine of the component i'm responsible of

### ISSUE THREAD

**Issue by Luscha** [noi-techpark/infrastructure-v2#33]
As an Open Data Hub developer i want to be able to perform integration test on my local machine of the component i'm responsible of

The goal of this issue is, setup everything is needed to be able to make the port forward on my local machine to be able to test locally the new feature I'm developing. Port forwarding is one of the solution that could be used.

**Comment by clezag** [comment]
Closing this, currently mostly solved by bash scripts with `kubectl port-forward` or `kubefwd`.
